# Generated by Django 5.0.2 on 2024-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dota 2', 'Dota 2'), ('CS:2', 'CS:2'), ('CoD Warzone', 'CoD Warzone'), ('LoL', 'LoL'), ('Apex Legends', 'Apex Legends'), ('Valorant', 'Valorant'), ('Fortnite', 'Fortnite')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='game',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(related_name='profiles', to='team_finder_app.game'),
        ),
    ]
