# Generated by Django 5.0.2 on 2024-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder_app', '0007_game_remove_profile_game_profile_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.AddField(
            model_name='profile',
            name='game',
            field=models.CharField(choices=[('Dota 2', 'Dota 2'), ('CS:2', 'CS:2'), ('CoD Warzone', 'CoD Warzone'), ('LoL', 'LoL'), ('Apex Legends', 'Apex Legends'), ('Valorant', 'Valorant'), ('Fortnite', 'Fortnite')], default='Dota 2', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
