# Generated by Django 4.2.5 on 2024-05-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_finder_app', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
